# Generated by Django 5.2.8 on 2025-11-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaIngredientes',
            new_name='CategoriaIngrediente',
        ),
    ]
