# Generated by Django 5.2.7 on 2025-10-30 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fechaPublicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
